DELETE FROM CANCELAMENTO WHERE id_cancelamento = 1;

DELETE FROM PAGAMENTO WHERE id_pagamento = 1;

DELETE FROM RESERVA WHERE id_reserva = 1;

DELETE FROM VAGA WHERE id_vaga = 1;

DELETE FROM QUARTO WHERE id_quarto = 1;

DELETE FROM CLIENTE WHERE id_cliente = 1;
