--todos registros
SELECT * FROM CLIENTE;
SELECT * FROM QUARTO;
SELECT * FROM VAGA;
SELECT * FROM RESERVA;
SELECT * FROM PAGAMENTO;
SELECT * FROM CANCELAMENTO;

--um registro por tabela
SELECT * FROM CLIENTE WHERE id_cliente = 1;
SELECT * FROM QUARTO WHERE id_quarto = 1;
SELECT * FROM VAGA WHERE id_vaga = 1;
SELECT * FROM RESERVA WHERE id_reserva = 1;
SELECT * FROM PAGAMENTO WHERE id_pagamento = 1;
SELECT * FROM CANCELAMENTO WHERE id_cancelamento = 1;
